### ISSUE TITLE
在unraid 安装了docker版的luckyBackup，设定了排程任务，无法自动启动，请问是有隐藏步骤要另外设置吗？

### ISSUE THREAD

**Issue by flykingworld** [ich777/luckyBackup#1]
在unraid 安装了docker版的luckyBackup，设定了排程任务，无法自动启动，请问是有隐藏步骤要另外设置吗？

**Comment by ich777** [comment]
> 在unraid 安装了docker版的luckyBackup，设定了排程任务，无法自动启动，请问是有隐藏步骤要另外设置吗？

If my translation software is correct I‘m assuming your are refering to the cron schedules correct?

Please read the description from the container again:

‘Cron: If you create a cron job please be sure to tick the "Console Mode" checkbox, otherwise the cron jobs will not work.‘

**Comment by ich777** [comment]
Closing due to no response. If you have any further questions feel free to reopen the issue or create a new issue.
